### ISSUE TITLE
Запрос документации по формату CDR

### ISSUE THREAD

**Issue by pawka35** [sergle/CDR-Parser-SI3000#1]
Сергей, доброго времени суток.
Подскажите не осталось ли у вас со времен разработки документации по формату CDR SI-3000? Если да - не могли бы вы ее предоставить?
То что я смог найти в сети относится к 2010 году и там есть описания полей только до 150-ого. У вас же в исходниках есть:

> TODO NOT IMPLEMENTED YET:
> .....
>  151. Call Type
>  152. IN Service Data
>  153. URI (Universal Resource Identification)
>  154. Free Format Operator Specific Data
>  155. -----
>  156. Additional Numbers

Т.е, судя по всему информация об этих полях у вас была.

**Comment by sergle** [comment]
Если еще актуально - напишите на email который указан в модуле.
